FROM node:22 AS build

WORKDIR /usr/src/app

COPY . .
RUN npm install
RUN npm run build --prod

FROM nginx
COPY --from=build /usr/src/app/dist/angular_auth_app /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
