FROM node AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build --prod

FROM node:16-alpine
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/dist /usr/src/app

RUN npm install -g http-server
EXPOSE 8080

CMD ["http-server", "-p", "8080"]
